---
title: "**Community Projects**"
output: html_document
---

<br>
## **Community Service for Statistical Analysis**

We provide statistical services for a non-profit organization located in Calgary.  The workflow of this service as below:

1. Please contact Chel via <<imstatsbee@gmail.com>> <s>Filling out the intake form and email the form to one of organizers (we are currently preparing the intake form)</s> 
<!--[Alice Lam](https://www.linkedin.com/in/alice-lam-71796238/){target="_blank"} <<alicelam22@gmail.com>> -->


2. You are going to be invited to give a background information about the problem of interest for 15 minutes. 

3. A special task team is made up of a small group of volunteers. 

4. An analysis is carried out for three months (by default) up to six months. 

5. The project is listed under the **ongoing projects** section.

6. You are presenting the outcome.  

Note that a service time cannot be asked to be shorten and a quality of service cannot be guaranteed since the only available resources are personal time and efforts from volunteers. 
    
