---
title: "**Meetings in 2021 (Virtual)**"
output: html_document
---

<br>


#### 2021-DEC-08 [Introduction to Shiny App in R](https://www.meetup.com/calgaryr/events/282151176/){target="_blank"}

+ Speaker: [<b>David Aponte</b>](Jose Aponte <daponte08@gmail.com>){target="_blank"}
+ Location: Online Event

\


Please welcome our speaker, David Aponte, PhD Candidate in medical science at the University of Calgary.

Shiny is an R framework for interacting with data through a web app. If you have complex data that is either continuously updated or big enough for people to explore for their own insights, Shiny is a fantastic library for creating visual tools to open up your data to the broader community. Shiny apps can easily be deployed to the web, allowing others to leverage your data and analyses without the fuss of installing anything or writing code.

In this workshop, we will learn the basics of making a Shiny application, starting with how you can take your existing analyses and make them work with user selectable inputs. We’ll also go over some tips for making your Shiny app work efficiently and look slick. Finally, we will go over deploying your Shiny application to a live website for anyone to use.

If you’d like to follow along with the workshop, make sure to download the Github repository from https://github.com/J0vid/CalgaryR_Shiny The GitHub readme briefly outlines the goals of the workshop, as well as potential future topics.

About the speaker:

David Aponte is a PhD Candidate in medical science at the University of Calgary. His dissertation work has focused on how genetic variation produces facial shape variation in mice and humans. He has used R for a wide array of projects like measuring color patterns from image data and identifying genetic syndromes from measurements of facial shape.

\

#### 2021-NOV-16 **Tuesday at 5 pm** [R Package DIY](https://www.meetup.com/calgaryr/events/281143383/){target="_blank"}

+ Speaker: [<b>Fonti Kar</b>](f.kar@unsw.edu.au){target="_blank"}
+ Location: Online Event

\

Please welcome our speaker, Dr. Fonti Kar, Postdoctoral Research Fellow at University of New South Wales, Sydney, Australia.

Do you have a few custom functions on heavy rotation?

Perhaps you have a piece of code that you regularly share with colleagues? Maybe you want to include your analysis code alongside a publication? Why not put it all in an R package?!

This interactive workshop will equip you with the basic skills to create an R package of your own!

Participants should have:

1) a Github account;
2) the most recent version of R and RStudio installed;
3) the following package(s) and their dependencies installed: devtools, testthat, knitr.

Dr. Kar is an evolutionary biologist at heart but is currently working as an R package developer. She works alongside researchers to develop R software tools for the research community. Her interests include biostatistics, reproducible science, learning about the latest coding practices and teaching others to enjoy using R. She is the founder of UNSWcodeRs - a university R user community where students and staff can learn new skills and find coding support.

\




#### 2021-NOV-03 at 5:30 pm [Meta-analysis in Medical Research: A Critical Appraisal and Brief Tutorial](https://www.meetup.com/calgaryr/events/281143383/){target="_blank"}

+ Speaker: [<b>Stephana Julia Moss</b>](stephana.moss@ucalgary.ca){target="_blank"}
+ Location: Online Event

\

A systematic review and meta-analysis is a scientific exercise that impacts healthcare and health policy. Readers of systematic reviews and meta-analyses may be patients, clinicians, administrators, or policymakers and therefore possess a wide range of skill in understanding research terms. It is important that authors of systematic reviews and meta-analyses make every effort to guide readers in making the best use of results in myriad clinical contexts and settings. Dr. Moss will present a critical appraisal of the methodological approach of a published systematic review and meta-analysis that culminates with a brief tutorial that compares the statistical approach to meta-analysis in STATA and R.

Dr. Moss received her BSc in Biochemistry from the University of Calgary, her MSc in Pharmacology from the University of Alberta, and her PhD in Epidemiology from the University of Calgary. Her most important scholarly contributions to date have centered on how to best partner with citizens in research. Thought leaders and funding agencies have been advocating with limited success for years for researcher-citizen partnerships to maximize the relevance and impact of scholarly work. Dr. Moss’s work epitomizes the value of this conceptual approach.

\

#### 2021-SEP-29 [Using R for Geographic Information System (GIS) and Landscape Analyses](https://www.meetup.com/calgaryr/events/280192457/){target="_blank"}

+ Speaker: [<b>Danielle Clake</b>](danielle.clake@ucalgary.ca){target="_blank"}
+ Location: Online Event

\

The loss of habitat is a well-known challenge facing global biodiversity, but we still require a better understanding of how specific aspects of landscape changes can affect communities. For example, while the amount of habitat available to a species is known to be important for its survival, there can also be an influence of the configuration of that habitat into one or many patches, or of the patches into either simple or complex shapes. Different landscape metrics have been developed to characterize these and other differences between habitats. R provides useful tools to calculate and assess landscape metrics, and to integrate the results into downstream analysis and modelling. 

In this talk I will provide a brief overview of the basics of spatial data and geographic information system (GIS) analysis in R, using the sf and raster packages to create and visualize spatial data. I will then show how the landscapemetrics package can be used to characterize the composition and configuration of landscapes. 

My research on bumble bee (Bombus sp.) habitat in the Rocky Mountains is an example of how these types of landscape analyses can be applied to test hypotheses about the relationships between species and the landscapes that they inhabit. I will discuss my findings in this project, and the various uses of R throughout.

\


#### 2021-APR-21 [Exploring Alberta’s Solar Resource through R](https://www.meetup.com/calgaryr/events/277113865/){target="_blank"} 

+ Speaker: [<b>Abed W Ayyad</b>](https://manipulativegerbil.blogspot.com/){target="_blank"}
+ Location: Online Event
+ [RSVP at https://www.meetup.com/calgaryr/events/277113865/](https://www.meetup.com/calgaryr/events/277113865/){target="_blank"}
+ [ [Zoom video recording] ](https://www.youtube.com/watch?v=JddDAqsUWhM&feature=youtu.be){target="_blank"}
+ [ [An extended version of the slides is available from here] ](./archives/2021_04_21/abed_ayyad_beamer_slides_for_calgary_rug_21_april.pdf){target="_blank"}
+ [ [Full R Codes used for this talk are available from here] ](./archives/2021_04_21/codes_for_abed_ayyad_presentation_pablo_help.R){target="_blank"}

<b>Synopsis</b>: Solar energy converted to electricity (photovoltaic, or PV, electricity) seems almost too good to be true when it comes to thinking about ways of reducing global carbon emissions. According to a widely repeated claim, one hour's worth of the solar radiation which falls on the earth's surface could meet human energy needs for one year. Though impressive and technically "correct", this is far from being a practical or meaningful calculation. So how much carbon-neutral electricity could someone sitting in the Canadian prairies actually harvest from the sunshine falling on their backyard? 

The amount of solar radiation arriving at an individual's home is "variable," it depends on geographic location (latitude especially, but also longitude) and on the time of year (seasonality); it also depends on the time of day (solar energy is "intermittent"). In addition, there is an upper limit to the amount of solar radiation which a PV panel can convert into electricity. We will define the proportion of PV electricity generated to solar radiation received as the "efficiency" of such a panel (note that other definitions of PV efficiency exist in the literature). This efficiency is in turn a function of the composition of the PV cells making up the panel and the prevailing temperatures, wind speeds and irradiance (solar energy per unit of time) at the panel's location. Keeping everything else fixed, if you have a (relatively coarse) hourly dataset of solar radiation, you have 8760 data points in a non-leap year. A more complete dataset would likely contain around 500,000 observations at 30-second intervals (this assumes that the sun shines for approximately ~50% of hours in the year) of several different variables all of which contribute to the amount of PV electricity generated during a given interval. 

R lends itself perfectly to the data intensive task of planning and predicting the amount of solar insolation which falls on a given location, and the electricity which one can expect to harvest from it. Following a (very) broad introduction to solar energy and photovoltaics, we will explore a number of packages available in R which make it possible to access and analyse publicly available data on solar insolation, and to understand what this might mean in terms of solar PV potential at a site in Alberta. We will accomplish the latter by doing a walk-through of an example using the nasapower package available in CRAN, as well as a number of the graphics and GIS-related packages also available in R. This talk, aimed at a wide audience of R users, will illustrate why Alberta is a surprisingly perfect location for solar PV deployment and how you can convince yourself of that using R.

<b>About the speaker</b>: I have used R in a variety of settings for seven years now, for GIS/cartography applications, data analysis and linear optimisation. There are many reasons to love R, but the community of users is definitely one of the biggest. Last September, Edmonton became the 10th city which I have called home during my life. I'm looking forward to discovering more of the city, and to cycling to some parks and lakes as the summer goes on and the days get longer. 


\

