---
title: "CalgaryR Meeting 2020"
output: html_document
date: updated on `r Sys.Date()` since 2019-04-30 
---


## About CalgaryR 2020

Welcome to the inaugural annual CalgaryR Meeting, hosted by the CalgaryR User Group. Join your fellow R practioners and learn how to use R over variety of disciplines within academia and industry, on May 16, 2020.

This event is open to all skill levels, industries and backgrounds. We invite all those who wish to collaborate, learn and celebrate our skills and diversity.

## Location & Date

Saturday May 16, 2020

8:00 to 17:00

University of Calgary (Engineering?)

## Registration Details & Link

Registration link will be open here on January 15, 2020.

Included with your registration fee is:

- Breakfast and Lunch
- Morning workshop
- Afternoon sessions

### Important Dates and Deadlines

September 15, 2019 - Formal launch of the CalgaryR Meeting 2020

January 15, 2020 - Registration opens

January 30, 2020- Abstract submission deadline

May 16, 2020 - CalgaryR Meeting 2020!

## Workshop

To be announced shortly!

## Speaker Sessions

Thank you for sharing your knowledge and moving the R community forward!

We are now accepting abstract submissions for R-focused applications related to the below topics and industries. Accepted abstracts will be presented by the author at Meeting 2020, with an expected duration of 20-25 minutes in length (including a 5 minute question and answer period). Please send abstract submissions to [](mailto:). Chairs will review and notify of abstract acceptance.

1. Health, Life Science, Social Science (Chair: T.L.)

2. Energy, Oil and Gas, Renewable Energy (Chair: J.F.)

3. TBA, Finance, Economics (Chair: K.R.)

4. Open data (Chair: )

### Abstract Format 

R needs to be used as the part of work. 

### Agenda 

8:30 Registration and breakfast

8:45 Opening acknowledgement

9:15 Workshop 

11:15 Job Fair & Networking Lunch (by Andrey Sivyakov)

13:00 Session 1

14:00 Session 2

15:00 Session 3

16:00 Closing 

### Partners & Sponsors 

The Meeting 2020 graciously thanks all our partners and members throughout the years, for their continued support and sponsorship of the CalgaryR community.

To become a partner member for the Meeting 2020, or if you would like your company to be representated at the job fair and networking session, please contact [Chel](mailto:chelhee.lee@ucalgary.ca). 

### Organizing Team 

* [Chel](mailto:chelhee.lee@ucalgary.ca)
* [Jonathan Lin](mailto:hello@jonlin.ca)
* [Dylan Loader](mailto:dylan.loader1@ucalgary.ca)
* [Ben Reeves](mailto:breeves@viewpointgroup.ca)
* [Andrey Sivyakov](mailto:asivyakov@suncor.com)

### Scientific Advisors

* [H.S.](mailto:)
* [A.W.](mailto:)
* [J.W.](mailto:)
* [T.W.](mailto:)
* [G.J.](mailto:)
