---
title: "**Meetings in 2022 (Virtual)**"
output: html_document
---

<br>


#### 2022-JAN-22 [Validation of the underlying construct of survey instruments](https://www.meetup.com/calgaryr/events/282613720/){target="_blank"}

+ Speaker: [<b>Cherri Zhang</b>](zhac@ucalgary.ca){target="_blank"}
+ Location: Online Event

\

Please welcome our speaker, Cherri Zhang, Data Manager and Analyst, Department of Psychology, University of Calgary. We are meeting virtually on Wednesday, January 12, 2022, at 5:30 pm

Abstract

Background: Diagnosis and management of concussion depends on post-concussive symptom (PCS) ratings. One approach to validation of PCS rating scales is to examine their factor structure and to test measurement invariance (MI).

Purpose: To validate the underlying construct of survey instruments across raters, groups, and time using confirmatory factor analysis (CFA) and MI through the implementation of lavaan package in R.

Methods: Four models were implemented: correlated two- and three-factor models and bifactor models with two and three specific factors across four levels of MI. MI is a stepwise approach that compares nested models by adding increasingly stringent constraints to model parameters. The MI levels are configural, weak, strong, and strict. Models were compared using fit indices such as root mean square error of approximation (RMSEA), comparative fit index (CFI), and Tucker-Lewis index (TLI). MI is established when the fit of the more stringent model (e.g., strong invariance) is no worse compared to the one with more relaxed assumptions (e.g., weak invariance), as indicated by fit statistics. Additionally, OmegaH was used to assess the bifactor models to estimate the proportion of observed variance in total and subscale scores that could be attributed to the underlying factors.

Results: The bifactor models displayed better fit indices; however, model convergence took up to several hours with the three-factor model having convergence problems during initial CFA. The correlated models showed greater parsimony, shorter convergence time, and less convergence issues. Strong to strict invariance were established in all models.

Conclusion: The findings support a two-factor model of the Health Behaviour Inventory (HBI). The bifactor model showed the best fit, suggesting that ratings on the HBI also can be captured by a general factor. The results provide further validation of the HBI, supporting its use in childhood concussion research and clinical practice.


\



#### 2022-MAR/APR [TBA](https://www.meetup.com/calgaryr/events/){target="_blank"}

+ Speaker: [<b>Volunteer</b>](){target="_blank"}
+ Location: Online Event


#### 2022-MAY/JUN [TBA](https://www.meetup.com/calgaryr/events/){target="_blank"}

+ Speaker: [<b>Volunteer</b>](){target="_blank"}
+ Location: Online Event


#### 2022-JUL/AUG [TBA](https://www.meetup.com/calgaryr/events/){target="_blank"}

+ Speaker: [<b>Volunteer</b>](){target="_blank"}
+ Location: Online Event


#### 2022-SEP/OCT [TBA](https://www.meetup.com/calgaryr/events/){target="_blank"}

+ Speaker: [<b>Volunteer</b>](){target="_blank"}
+ Location: Online Event


#### 2022-NOV/DEC [TBA](https://www.meetup.com/calgaryr/events/){target="_blank"}

+ Speaker: [<b>Volunteer</b>](){target="_blank"}
+ Location: Online Event
