---
title: "**Meetings in 2019-2020**"
output: html_document
---

#### 2019-SEP-18 [Event-Study Method, Similiarity, Susceptibility Ranking](https://www.meetup.com/calgaryr/events/263868941/){target="_blank"}

+ Location: Cenovus Odd Fellows
+ [RSVP at meetup](https://www.meetup.com/calgaryr/events/263868941/){target="_blank"}

+ Talk 1: **Burning out of Time: Power-Plant Decommissions and Mine Cloures in the Appalachians**, by [Reinaldo Viccini](https://www.linkedin.com/in/reinaldo-viccini-guti%C3%A8rrez-40171645?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3BzaorgguQRaWnPq6BuyEFLA%3D%3D){target="_blank"} <br><br> For the past 50 years, coal has been the most important fuel for electricity generation in the United States. The power sector on its own consumes 90% of all domestically mined coal and supplies 30% of the nation's energy demand. Facing serious challenges from low natural gas prices, environmental regulation and increasing operational costs, coal-fired power plants are being decommissioned at increasing rates. Similarly, since 2010, coal production has fallen by 28.5% and nearly half of the existing mines have permanently closed.   The purpose of this paper is to investigate the claim that power plant decommissions are causing closures and production declines in Appalachian mines. If decommissions are impacting mines in any way, given the regional nature of coal markets, nearby mines should be the most affected. The empirical strategy begins by testing the assumption that power plants buy local coal. I argue that observed differences in power plant efficiencies, by state and plant size, emerge as a consequence of local coal quality. Next, I estimate the correlations between aggregate electricity generation and coal consumption from nearby power plants on the mine's production (intensive margin) and probability of closure (extensive margin). Results suggest that changes in aggregate electricity generation and coal consumption from the 10 nearest plant’s have a larger impact on the local mine's intensive and extensive margin as compared to plants in further locations. Finally, using an event-study methodology, I estimate the causal effect of a decommission within the 10 nearest plants to the mine <br><br>
+ Talk 2: **Using unsupervised machine learning to tag oil and gas pressure drop methods used in commercial flow simulators**, by [Pablo Adames](https://www.linkedin.com/in/adames-pablo-87149711?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3B71saROFiRceFp2frfFszXQ%3D%3D){target="_blank"}<br><br> Oil and gas engineers rely on flow simulators to design and troubleshoot pipelines, wells, and thus the facilities needed to achieve production and operation targets within the safety and economic constraints.  Commercial software simulators offer a wide choice of calculation methods for the pressure drop and liquid holdup at every point of the system, these are usually referred to as `flow correlations` for historical reasons.  The difference in the numerical results of the simulations can vary significantly as a function of the flow method selected, leaving everything else constant. <br><br>
Unsupervised classification methods can be used to discover similarities in the results of the flow correlations available. Once the methods are tagged as belonging to a class of methods based on the similarity of the results, `a priory` knowledge can be used to assign meaning and make recommendations on the more consistent classes of methods to use in a particular production scenario.<br><br>
For this study, Schlumberger's PIPESIM was used to assess 35 different methods on a model built from field data in the public domain, a metric was defined to assess similarity, the machine learning results were compared to the empirical knowledge, and consistent results were identified for this specific production scenario.  The processing of the text files from the simulator and the subsequent statistical analysis and visualizations were done in R and the code is presented in reproducible research format using the package `knitr` and `RStudio`.  The data and files are also available in `Github`.<br><br>
+ Talk 3: **Asset Failure Susceptibility Ranking, using LambdaMART**, by [Busayo Akinloye](https://www.linkedin.com/in/busayo-akinloye-p-eng-7ba12028?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3Brxm2AxvQT6ahGLEjD270Ww%3D%3D){target="_blank"}<br><br> The electric distribution system is one of the most diverse systems in the electrical grid. It consists of both overhead and underground assets. Growing power quality and reliability expectations from regulatory authorities and customers demand minimal downtime of equipment. Metrics such as System Average Interruption Frequency Index (SAIFI), and System Average Interruption Duration Index (SAIDI) are closely being monitored by electric utilities and form a major part of the business’ performance indices. These growing expectations, coupled with aging assets and budget constraints require innovative and cost-effective ways to realize actionable intelligence in order to optimize spending, while improving or maintaining the quality and reliability of the electric grid.
Data analysis offers a unique solution that is reproducible across all asset infrastructure of an electric grid. It employs complex machine learning and statistical algorithms to extract actionable insights and learnings from historical data. These insights will help utilities better allocate both financial and human resources to the most failure susceptible assets, truly making data-driven decisions.
I will discuss the development of an asset failure susceptibility ranking system on the Calgary area Underground Residential Distribution (URD) System. This system employs the supervised ranking system used by information retrieval systems. The framework of this ranking system can be applied to all distribution system assets (equipment), due to the reproducible nature of the statistical algorithms it employs.<br><br>

#### 2019-OCT-16 [title1 / title2](){target="_blank"}
+ Location: TBA
+ [RSVP at meetup](){target="_blank"}

+ Talk 1: **Title** by [David Chan](https://www.linkedin.com/in/davidichan?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3BCd1WIB5RRCi6VVGLx1INPw%3D%3D){target="_blank"} (confirmed)

Waiting for abstract 

+ Talk 2: **Title** by [Naoko Tomioka](https://www.linkedin.com/in/naoko-tomioka-038108b?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3BoYo7F26eTFunf2Yjv%2BChMQ%3D%3D){target="_blank"} (confirmed)

Waiting for abstract 

+ Talk 3: **Title** by [Drew Gilson](https://www.linkedin.com/in/drewgillson?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3BGHewhCPhS6CCUxkRUC9aDw%3D%3D){target="_blank"}


<br>

#### 2019-NOV-20 [title1 / title2](){target="_blank"}
+ Location: TBA
+ [RSVP at meetup](){target="_blank"}

+ Talk 1: David Shakleton () 

+ Talk 2: (in progress) <!-- Dr. uir -->

+ Talk 3: (in progress)

<br>

#### 2020-JAN-15 [title1 / title2](){target="_blank"} 
+ Location: TBA
+ [RSVP at meetup](){target="_blank"}

+ Talk 1: (in progress)

+ Talk 2: title, looking for a volunteer 

<br>

#### February 19, 2019 [title1 / title2](){target="_blank"}
+ Location: TBA
+ [RSVP at meetup](){target="_blank"}

+ Talk 1: title, looking for a volunteer 

+ Talk 2: (in progress) 

<br>

#### March 18, 2019
+ Location: TBA
+ [RSVP at meetup](){target="_blank"}

+ Talk 1: title, looking for a volunteer 

+ Talk 2: title, looking for a volunteer 
