---
title: "**For Community**"
output: html_document
---

<br>

## Open Data Projects 

### Data Sources 

* [AESO](ets.aeso.ca){target="_blank"}

* [Alberta Government Open Data](https://economicdashboard.alberta.ca/OilPrice){target="_blank"}

* [Alberta Energy Regulator](https://www.aer.ca/providing-information/data-and-reports/statistical-reports){target="_blank"}

* [ABMI](http://www.abmi.ca/home/data-analytics/da-top/da-product-overview){target="_blank"}

* [City of Calgary - Open Calgary](https://data.calgary.ca/){target="_blank"}.  

* [Calgary Civic Census](http://www.calgary.ca/CA/city-clerks/Pages/Election-and-information-services/Civic-Census/CensusResults.aspx){target="_blank"}

* [Calgary Police Service Statistical Reports](http://www.calgary.ca/cps/Pages/Statistics/Calgary-Police-statistical-reports.aspx){target="_blank"}

* [Data Hub from National Energy Board](https://www.neb-one.gc.ca/rsrccntr/dthb/index-eng.html){target="_blank"}

* [Market Data from TMX WebStore for TSX and TSXV](https://www.tmxwebstore.com/products/#q=%7Cc=44%7Cm=%7Cpage=1){target="_blank"}

<br>

## **Personal Projects**

1. **Calgary Police Crime Statistics** - This dataset was chosen in our first meeting in 2017.  The purpose was to use it as a common source that members can practice R programming techniques.  We decided in the second meeting to use it for a community year project.  

2. **Writing about cities, urban planning, mapping, data visualization & creative coding** led by [Saadiq Mohiuddin](https://saadiqm.com/){target="_blank"} 

3. **A project to design and maintain a standardized, R based, slide presentation format. The project is currently based in Xaringan written by Yihui Xie at Rstudio** led by [Dylan Loader](https://github.com/DylanLoader/CalgaryR-presentation){target="_blank"}

<br>


## **Community Service for Statistical Analysis**

We provide statistical services for a non-profit organization located in Calgary.  The workflow of this service as below:

1. Please contact Chel via <<imstatsbee@gmail.com>> <s>Filling out the intake form and email the form to one of organizers (we are currently preparing the intake form)</s> 
<!--[Alice Lam](https://www.linkedin.com/in/alice-lam-71796238/){target="_blank"} <<alicelam22@gmail.com>> -->


2. You are going to be invited to give a background information about the problem of interest for 15 minutes. 

3. A special task team is made up of a small group of volunteers. 

4. An analysis is carried out for three months (by default) up to six months. 

5. The project is listed under the **ongoing projects** section.

6. You are presenting the outcome.  

Note that a service time cannot be asked to be shorten and a quality of service cannot be guaranteed since the only available resources are personal time and efforts from volunteers. 
    
