---
title: "R-Medicine"
output: html_document
---

<br>

Thank you for the leadership of the [Centre for Health Informatics](https://cumming.ucalgary.ca/centres/centre-health-informatics){target="_blank"}.  Please contact [Catherine Eastwood](mailto:caeastwo@ucalgary.ca) for questions.

<br>

### Dates for Meetings

<br>

Venue: [5th floor, TRW buidling, 3280 Hospital Dr NW, Calgary](https://cumming.ucalgary.ca/centres/centre-health-informatics/about/space){target="_blank"}

Thursday in the first week of every month at 5:30 pm 
<br>

* September 5, 2019 - nonlinear modeling with R, led by chel  

[RSVP at meetup] (maximum capacity 30)
<br>

* October 3, 2019 - introduction to R programming, led by chel 

data structure, manipulation and cleaning techniques

target audience: anyone who is interested in learning R 

[RSVP at meetup] (maximum capacity 30)
<br>

* November 7, 2019 - looking for a volunteer to speak

[RSVP at meetup] (maximum capacity 30)
<br>

* December 5, 2019 - looking for a volunteer to speak

[RSVP at meetup] (maximum capacity 30)
<br>

* ~~January 2, 2020~~ (Holiday) 

* February 6, 2020 - looking for a volunteer to speak  

[RSVP at meetup] (maximum capacity 30)
<br>

* March 5, 2020 - looking for a volunteer to speak

[RSVP at meetup] (maximum capacity 30)
<br>

* April 2, 2020  - looking for a volunteer to speak 

[RSVP at meetup] (maximum capacity 30)
<br>

<!-- Student Presentation from DataSci Program -->


### Mentors and Advisors  

* [Christian Job McIntosh](mailto:) for topic 
* [Danijela Piskulic](mailto:) for topic 
* contact for topic 


### Topics of interest

Clinical trial, medical image, ecg reading,  cancer study, study design for SPOR, personalized medicine, cancer data, health services, etc 

### Statistical models/techniques:
  + infectious disease model
  + disease mapping 
  + text summarization and sentiment analysis 
  + medical chart parsing 
  + survey response
  + survial analysis / repeated measures / functional data analysis 
  + time series / cosinor / wavelets / fourier  
  + joint model of longitudinal and survival data 
  + imaging data/neural network / CNN / RNN / 
  + agreement of mesurement systems
  + decision tree/predictive modeling 
  + Bayesian analysis 
  
